name: dataset-6e09efb3-6f77-4422-949c-0c2b047cd17a
functions:
  max_inputs: 20
  num_generations: 2
  batch_size: 10
instructions:
  num_generations: 10
  batch_size: 10
responses:
  num_generations: 2
  batch_size: 10
feedback:
  num_generations: 2
  batch_size: 10
dataset_paths:
  responses: data/dataset-6e09efb3-6f77-4422-949c-0c2b047cd17a/2024-02-09-15-31-49/checkpoints/responses