name: fml-generation
save_frequency:   
data:
  input:
    feedback: data/fml-generation/2024-02-14-10-15-15/checkpoints/feedback 
  output:
    argilla: fml-generation
generation:
  functions:
    max_inputs: 20
    num_generations: 2
    batch_size: 10
  instructions:
    num_generations: 10
    batch_size: 10
  responses:
    num_generations: 2
    batch_size: 10
  feedback:
    num_generations: 1
    batch_size: 3
expansion:
  non_calls:
    max_inputs: 2
    num_generations: 2
    batch_size: 5
  distractors:
    max_distractors: 3
    max_inputs: 50
  feedback:
    num_generations: 2
    batch_size: 10


  
  

  