name: dataset-6e09efb3-6f77-4422-949c-0c2b047cd17a
functions:
  max_inputs: 20
  num_generations: 2
  batch_size: 10
instructions:
  num_generations: 10
  batch_size: 10
reponses:
  num_generations: 2
  batch_size: 10
feedback:
  max_inputs: 100
  num_generations: 2
  batch_size: 10
